Failed: module-types/MikroTik/RBGPOE.yaml failed validation: Additional properties are not allowed ('poe' was unexpected)
Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}
tests/definitions_test.py::test_definitions[module-types/MikroTik/RBGPOE.yaml-schema9-A] FAILED [100%]

=================================== FAILURES ===================================
________ test_definitions[module-types/MikroTik/RBGPOE.yaml-schema9-A] _________
Additional properties are not allowed ('poe' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}

During handling of the above exception, another exception occurred:
module-types/MikroTik/RBGPOE.yaml failed validation: Additional properties are not allowed ('poe' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}
=========================== short test summary info ============================
FAILED tests/definitions_test.py::test_definitions[module-types/MikroTik/RBGPOE.yaml-schema9-A] - Failed: module-types/MikroTik/RBGPOE.yaml failed validation: Additional properties are not allowed ('poe' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}