PH22-9D1-P SHTK-M-18.6.8-3AAA (#3758)
* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* Update BX750MI-GR.yaml

Fixed issues and cleanup

* Update BX750MI-GR.yaml

* BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* APC BX750MI-GR

* PDU-8P.yaml

* Cabeus PDU-8P

* Cabeus PDU-8P

* cabeus-pdu-8p

* Cabeus PDU-8P

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDCPL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* PL-24-Cat-5e-Dual-IDC

* Update PL-24-Cat-5e-Dual-IDC.yaml

* fixed filename

* EPP3-10-12-8P8C-C6-110D

* exegate-epp3-10-12-8p8c-c6-110d

* exegate-epp3-10-12-8p8c-c6-110d

* exegate-epp3-19-24-8p8c-c6-110d

* exegate-epp3-19-24-8p8c-c6-110d

* exegate-epp3-19-24-8p8c-c6-110d

* exegate-epp3-19-24-8p8c-c6-110d

* exegate-epp3-19-24-8p8c-c6-110d

* EPP3-10-12-8P8C-C6-110D

* exegate-eppw-12-8p8c-c5e-fr

* hikvision

* ikvision-ds-7616nxi-k2

* update

* "

* hikvision-ds-2cd2047g2-luc

* hikvision-ds-7616nxi-k2

* hikvision-ds-7616nxi-k2

* hikvision-ds-7616nxi-k2

* hikvision-ds-7616nxi-k2

* hikvision-ds-7616nxi-k2

* other

* hikvision-ds-7616nxi-k2

* hikvision-ds-7616nxi-k2-1u

* hikvision-ds-7616nxi-k2-1u

* hiwatch-ds-i252l

* hiwatch-ds-i252l

* itk-co05-1pc

* itk-co05-1pc

* Fixed issues

* MikroTik cAP ax cAPGi-5HaxD2HaxD

* MikroTik cAP ax cAPGi-5HaxD2HaxD

* MikroTik cAP ax cAPGi-5HaxD2HaxD

* MikroTik cAP ax cAPGi-5HaxD2HaxD

* MikroTik cAP ax cAPGi-5HaxD2HaxD

* MikroTik cAP ax cAPGi-5HaxD2HaxD

* MikroTik cAP ax cAPGi-5HaxD2HaxD

* mikrotik-ccr2004-16g-2s-plus

* mikrotik-crs112-8p-4s-in

* mikrotik-crs112-8p-4s-in

* mikrotik-crs326-24g-2s-plus-rm

* mikrotik-crs326-24g-2s-plus-rm

* mikrotik-hap-ac-lite-tc

* mikrotik-cap-xl-ac

* mikrotik-cap-xl-ac

* mikrotik-cap-ac

* RBD52G-5HacD2HnD-TC

* netlinkfd-6166-2xrj-45-8p-8c-5

* FD-6166-2xRJ-45-8p-8c-5

* FD-6166-2xRJ-45-8p-8c-5

* FD-6166-2xRJ-45-8p-8c-5

* FD-6166-2xRJ-45-8p-8c-5

* ruijie-rg-nbs3100-24gt4sfp-p

* FD-6166-2xRJ-45-8p-8c-5

* FD-6166-2xRJ-45-8p-8c-5

* fd-6166-2xrj-45-8p-8c-5.yaml

* fd-6166-2xrj-45-8p-8c-5

* fd-6166-2xrj-45-8p-8c-5

* netlink-fd-6166-2хrj-45-8р-8с-5.front

* fd-6166-2xrj-45-8p-8c-5

* CCR2004-16G-2S+

* securitycode-ipc-50

* securitycode-ipc-10

* securitycode

* Securitycode

* SecurityCode

* SecurityCode

* smartlabs-sml-482-hd-base

* SNR-S5210G-24TX

* snr-s5210g-24tx

* snr-s5210g-24tx

* snr-s5210g-24tx

* snr-s5210g-24tx

* snr-s5210g-24tx

* snr-s5210g-24tx

* snr-ups-onrt-1000-s24

* UPS-ONRT-1000-S24 ELEMENT II

* SNR-UPS-ONRT-1000-S24

* UPS-ONRT-1000-S24 ELEMENT II

* snr-ups-onrt-1000-s24

* snr-ups-onrt-1000-s24

* SNR-UPS-ONRT-1000-S24

* UPS-ONRT-1000-S24 ELEMENT II

* SNR UPS-ONRT-1000-S24 ELEMENT II

* UPS-ONRT-1000-S24 ELEMENT II

* SNR-UPS-ONRT-1000-S24 ELEMENT II

* SNR-UPS-ONRT-1000-S24 ELEMENT II

* sysmatrix-abs-pd-0802-000

* SYSMATRIX ABS-PD 0802.000

* SYSMATRIX ABS-PD 0802.000

* sysmatrix-abs-pd-0802.000

* ABS-PD-0802-000

* PD-0802.000

* sysmatrix-abs-pd-0802-000

* tp-link-archer-ax1800

* archer-ax1800

* xiaomi-mi-router-4c

* xiaomi-mi-router-4c

* xiaomi-mi-router-4c

* xiaomi-mi-router-4c

* mi-router-4c

* xiaomi-l32m7-earu

* xiaomi-l32m7-earu

* zastava-150

* zastava-150

* zastava-150

* zastava-zastava-150

* zastava-150

* zastava-150

* zastava-zastava-150

* DL801

* NetAgent9 MiniGO

* NetAgent9 MiniGO

* DL801 NetAgent9 MiniGO

* RBGPOE

* Failed: module-types/MikroTik/RBGPOE.yaml failed validation: Additional properties are not allowed ('poe' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}
tests/definitions_test.py::test_definitions[module-types/MikroTik/RBGPOE.yaml-schema9-A] FAILED [100%]

=================================== FAILURES ===================================
________ test_definitions[module-types/MikroTik/RBGPOE.yaml-schema9-A] _________
Additional properties are not allowed ('poe' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}

During handling of the above exception, another exception occurred:
module-types/MikroTik/RBGPOE.yaml failed validation: Additional properties are not allowed ('poe' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}
=========================== short test summary info ============================
FAILED tests/definitions_test.py::test_definitions[module-types/MikroTik/RBGPOE.yaml-schema9-A] - Failed: module-types/MikroTik/RBGPOE.yaml failed validation: Additional properties are not allowed ('poe' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['rear-ports']['items']:
    {'type': 'object',
     'properties': {'name': {'type': 'string', 'maxLength': 64},
                    'label': {'type': 'string', 'maxLength': 64},
                    'type': {'$ref': 'urn:devicetype-library:generated-schema#/definitions/rear-port/properties/type'},
                    'color': {'type': 'string', 'pattern': '^[a-f0-9]{6}$'},
                    'positions': {'type': 'integer', 'minimum': 1},
                    'description': {'type': 'string'},
                    '_is_power_source': {'$ref': 'urn:devicetype-library:reusable#/definitions/_is_power_source'}},
     'required': ['name', 'type'],
     'additionalProperties': False}

On instance['rear-ports'][0]:
    {'name': 'OUT',
     'label': 'OUT',
     'type': '8p8c',
     'positions': 1,
     'poe': True,
     'description': 'POE-OUT'}

* RBGPOE1

* RBGPOE

* RBPOE

* G1040A-60WF

* G1040A-60WF

* APC

* BX650CI-RS

* SDN4400160

* schneider-electric-sdn4400160

* SDN3000560

* w&t-wt-2261a-ger

* w-t-wt-2261a-ger

* w-t-wt-2261a-ger

* DGS-1100-08PLV2

* d-link-dgs-1100-08plv2

* d-link-dgs-1100-08plv2

* d-link-dgs-1100-08

* d-link-dgs-1100-08v2

* d-link-dgs-1100-08v2

* powercom-wow-300

* powercom-wow-300

* powercom-wow-300

* most-a10-1-6

* most-a10-1-6

* most-a10-1-6

* most-a10-1-6

* most-a10-1-6

* update

* Most A10-3

* SHTK-M-18.6.8-3AAA PH22-9D1-P

* SHTK-M-18.6.8-3AAA

* PH22-9D1-P

* cmo-shtk-m-18-6-8-3aaa

---------

Co-authored-by: Harry <Harry@cadby.co.uk>
Co-authored-by: zaika-nv <nzaika@digital-spirit.ru>